// Auto-generated by Revenant. Do not edit by hand.
import * as rawWasm from 'prime_sieve_wasm';

export function is_prime(n: number): boolean {
	return rawWasm.is_prime(n);
}

export function primes_up_to(limit: number): Uint32Array {
	return rawWasm.primes_up_to(limit);
}

export function prime_count(limit: number): number {
	return rawWasm.prime_count(limit);
}

const wasm = {
	is_prime,
	primes_up_to,
	prime_count,
};

export default wasm;
