use anyhow::{Context, Result};
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
use syn::{
    Fields, FnArg, GenericArgument, Item, ItemEnum, ItemFn, ItemStruct, Pat, PathArguments,
    ReturnType, Type,
};

use crate::config::{RUST_SUBDIR, WASM_OUT_DIR, WEB_SUBDIR, wasm_package_name};

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct ContractManifest {
    pub exports: Vec<ExportContract>,
    pub types: Vec<TypeDefinition>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct ExportContract {
    pub name: String,
    pub args: Vec<FieldContract>,
    pub return_type: ContractType,
    pub bridge: BridgeStrategy,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct FieldContract {
    pub name: String,
    pub ty: ContractType,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum BridgeStrategy {
    Direct,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum TypeDefinition {
    Struct {
        name: String,
        fields: Vec<FieldContract>,
    },
    TupleStruct {
        name: String,
        items: Vec<ContractType>,
    },
    Enum {
        name: String,
        variants: Vec<EnumVariant>,
    },
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EnumVariant {
    Unit {
        name: String,
    },
    Tuple {
        name: String,
        items: Vec<ContractType>,
    },
    Struct {
        name: String,
        fields: Vec<FieldContract>,
    },
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ContractType {
    Unit,
    Boolean,
    Number {
        rust: String,
    },
    String,
    Vec {
        item: Box<ContractType>,
    },
    Option {
        item: Box<ContractType>,
    },
    Result {
        ok: Box<ContractType>,
        err: Box<ContractType>,
    },
    Tuple {
        items: Vec<ContractType>,
    },
    Named {
        name: String,
    },
}

#[derive(Clone)]
enum RawTypeDef {
    Struct(ItemStruct),
    Enum(ItemEnum),
}

pub fn sync_bindings(project_root: &Path, project_name: &str) -> Result<()> {
    let rust_lib_path = project_root.join(RUST_SUBDIR).join("src").join("lib.rs");
    let source = std::fs::read_to_string(&rust_lib_path)
        .with_context(|| format!("failed to read {}", rust_lib_path.display()))?;

    let manifest = build_manifest(&source)?;
    let wrapper = generate_wrapper(project_name, &manifest)?;
    let manifest_json =
        serde_json::to_string_pretty(&manifest).context("failed to serialize contract manifest")?;

    let pkg_dir = project_root.join(WASM_OUT_DIR);
    let web_lib_dir = project_root.join(WEB_SUBDIR).join("src").join("lib");
    std::fs::create_dir_all(&pkg_dir)
        .with_context(|| format!("failed to create {}", pkg_dir.display()))?;
    std::fs::create_dir_all(&web_lib_dir)
        .with_context(|| format!("failed to create {}", web_lib_dir.display()))?;

    write_if_changed(
        &pkg_dir.join("revenant.contract.json"),
        &(manifest_json + "\n"),
    )?;
    write_if_changed(&web_lib_dir.join("wasm.ts"), &wrapper)?;

    Ok(())
}

pub fn build_manifest(source: &str) -> Result<ContractManifest> {
    let file = syn::parse_file(source).context("failed to parse rust/src/lib.rs")?;

    let mut raw_defs = BTreeMap::new();
    let mut exports = Vec::new();

    for item in file.items {
        match item {
            Item::Struct(item) => {
                raw_defs.insert(item.ident.to_string(), RawTypeDef::Struct(item));
            }
            Item::Enum(item) => {
                raw_defs.insert(item.ident.to_string(), RawTypeDef::Enum(item));
            }
            Item::Fn(item) if is_wasm_bindgen_export(&item) => exports.push(item),
            Item::Impl(item) if has_wasm_bindgen_attr(&item.attrs) => {
                anyhow::bail!(
                    "found a #[wasm_bindgen] impl block. Revenant does not support struct \
                     methods yet — expose free `pub fn` functions instead."
                );
            }
            _ => {}
        }
    }

    let mut builder = ManifestBuilder::new(raw_defs);
    let mut export_contracts = Vec::new();

    for export in exports {
        export_contracts.push(builder.export_from_fn(&export)?);
    }

    Ok(ContractManifest {
        exports: export_contracts,
        types: builder.finish_types(),
    })
}

fn generate_wrapper(project_name: &str, manifest: &ContractManifest) -> Result<String> {
    let mut output = String::new();
    let import_name = wasm_package_name(project_name);

    output.push_str("// Auto-generated by Revenant. Do not edit by hand.\n");
    output.push_str(&format!("import * as rawWasm from '{import_name}';\n\n"));

    if uses_result(manifest) {
        output.push_str("export type RevenantResult<T, E> =\n");
        output.push_str("\t| { ok: true; value: T }\n");
        output.push_str("\t| { ok: false; error: E };\n\n");
    }

    for type_def in &manifest.types {
        render_type_definition(type_def, &mut output)?;
        output.push('\n');
    }

    for export in &manifest.exports {
        let args = export
            .args
            .iter()
            .map(|arg| Ok(format!("{}: {}", arg.name, render_direct_type(&arg.ty)?)))
            .collect::<Result<Vec<_>>>()?
            .join(", ");
        let arg_names = export
            .args
            .iter()
            .map(|arg| arg.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        let ret = render_direct_type(&export.return_type)?;

        output.push_str(&format!(
            "export function {}({args}): {ret} {{\n",
            export.name
        ));
        if matches!(export.return_type, ContractType::Unit) {
            output.push_str(&format!("\trawWasm.{}({arg_names});\n", export.name));
        } else {
            output.push_str(&format!("\treturn rawWasm.{}({arg_names});\n", export.name));
        }
        output.push_str("}\n\n");
    }

    output.push_str("const wasm = {\n");
    for export in &manifest.exports {
        output.push_str(&format!("\t{},\n", export.name));
    }
    output.push_str("};\n\n");
    output.push_str("export default wasm;\n");

    Ok(output)
}

fn render_type_definition(type_def: &TypeDefinition, output: &mut String) -> Result<()> {
    match type_def {
        TypeDefinition::Struct { name, fields } => {
            output.push_str(&format!("export interface {name} {{\n"));
            for field in fields {
                output.push_str(&format!(
                    "\t{}: {};\n",
                    field.name,
                    render_contract_type(&field.ty)?
                ));
            }
            output.push_str("}\n");
        }
        TypeDefinition::TupleStruct { name, items } => {
            let inner = items
                .iter()
                .map(render_contract_type)
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            output.push_str(&format!("export type {name} = [{inner}];\n"));
        }
        TypeDefinition::Enum { name, variants } => {
            output.push_str(&format!("export type {name} =\n"));
            for (index, variant) in variants.iter().enumerate() {
                let sep = if index + 1 == variants.len() {
                    ";"
                } else {
                    " |"
                };
                match variant {
                    EnumVariant::Unit { name: variant_name } => {
                        output.push_str(&format!("\t{{ tag: '{variant_name}' }}{sep}\n"));
                    }
                    EnumVariant::Tuple {
                        name: variant_name,
                        items,
                    } => {
                        let value = items
                            .iter()
                            .map(render_contract_type)
                            .collect::<Result<Vec<_>>>()?
                            .join(", ");
                        output.push_str(&format!(
                            "\t{{ tag: '{variant_name}'; value: [{value}] }}{sep}\n"
                        ));
                    }
                    EnumVariant::Struct {
                        name: variant_name,
                        fields,
                    } => {
                        let fields = fields
                            .iter()
                            .map(|field| {
                                Ok(format!(
                                    "{}: {}",
                                    field.name,
                                    render_contract_type(&field.ty)?
                                ))
                            })
                            .collect::<Result<Vec<_>>>()?
                            .join("; ");
                        output.push_str(&format!(
                            "\t{{ tag: '{variant_name}'; value: {{ {fields} }} }}{sep}\n"
                        ));
                    }
                }
            }
        }
    }

    Ok(())
}

fn render_contract_type(ty: &ContractType) -> Result<String> {
    Ok(match ty {
        ContractType::Unit => "null".to_string(),
        ContractType::Boolean => "boolean".to_string(),
        ContractType::Number { .. } => "number".to_string(),
        ContractType::String => "string".to_string(),
        ContractType::Vec { item } => format!("Array<{}>", render_contract_type(item)?),
        ContractType::Option { item } => format!("{} | null", render_contract_type(item)?),
        ContractType::Result { ok, err } => format!(
            "RevenantResult<{}, {}>",
            render_contract_type(ok)?,
            render_contract_type(err)?
        ),
        ContractType::Tuple { items } => {
            let items = items
                .iter()
                .map(render_contract_type)
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            format!("[{items}]")
        }
        ContractType::Named { name } => name.clone(),
    })
}

fn render_direct_type(ty: &ContractType) -> Result<String> {
    Ok(match ty {
        ContractType::Unit => "void".to_string(),
        ContractType::Boolean => "boolean".to_string(),
        ContractType::Number { .. } => "number".to_string(),
        ContractType::String => "string".to_string(),
        ContractType::Vec { item } => typed_array_name(item).with_context(|| {
            format!(
                "type {} can be described in TypeScript, but Revenant cannot bridge it directly yet",
                render_contract_type(ty).unwrap_or_else(|_| "Vec<_>".to_string())
            )
        })?,
        _ => anyhow::bail!(
            "type {} can be described in TypeScript, but Revenant cannot bridge it directly yet. \
             Stick to primitives/strings/typed numeric vectors for now.",
            render_contract_type(ty)?
        ),
    })
}

fn typed_array_name(item: &ContractType) -> Option<String> {
    let rust = match item {
        ContractType::Number { rust } => rust.as_str(),
        _ => return None,
    };

    Some(
        match rust {
            "u8" => "Uint8Array",
            "i8" => "Int8Array",
            "u16" => "Uint16Array",
            "i16" => "Int16Array",
            "u32" => "Uint32Array",
            "i32" => "Int32Array",
            "f32" => "Float32Array",
            "f64" => "Float64Array",
            _ => return None,
        }
        .to_string(),
    )
}

fn uses_result(manifest: &ContractManifest) -> bool {
    manifest.exports.iter().any(|export| {
        type_uses_result(&export.return_type)
            || export.args.iter().any(|arg| type_uses_result(&arg.ty))
    }) || manifest.types.iter().any(type_definition_uses_result)
}

fn type_definition_uses_result(type_def: &TypeDefinition) -> bool {
    match type_def {
        TypeDefinition::Struct { fields, .. } => {
            fields.iter().any(|field| type_uses_result(&field.ty))
        }
        TypeDefinition::TupleStruct { items, .. } => items.iter().any(type_uses_result),
        TypeDefinition::Enum { variants, .. } => variants.iter().any(|variant| match variant {
            EnumVariant::Unit { .. } => false,
            EnumVariant::Tuple { items, .. } => items.iter().any(type_uses_result),
            EnumVariant::Struct { fields, .. } => {
                fields.iter().any(|field| type_uses_result(&field.ty))
            }
        }),
    }
}

fn type_uses_result(ty: &ContractType) -> bool {
    match ty {
        ContractType::Result { .. } => true,
        ContractType::Vec { item } | ContractType::Option { item } => type_uses_result(item),
        ContractType::Tuple { items } => items.iter().any(type_uses_result),
        _ => false,
    }
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    let current = std::fs::read_to_string(path).ok();
    if current.as_deref() == Some(content) {
        return Ok(());
    }

    std::fs::write(path, content)
        .with_context(|| format!("failed to write generated file {}", path.display()))
}

fn is_wasm_bindgen_export(item: &ItemFn) -> bool {
    if !matches!(item.vis, syn::Visibility::Public(_)) {
        return false;
    }

    has_wasm_bindgen_attr(&item.attrs)
}

/// True if `generics` has any type or const parameter. Lifetime-only generics
/// (e.g. `fn greet<'a>(name: &'a str) -> &'a str`) are bridgeable and don't count.
fn has_non_lifetime_generics(generics: &syn::Generics) -> bool {
    generics
        .params
        .iter()
        .any(|p| !matches!(p, syn::GenericParam::Lifetime(_)))
}

fn has_wasm_bindgen_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path()
            .segments
            .last()
            .is_some_and(|segment| segment.ident == "wasm_bindgen")
    })
}

struct ManifestBuilder {
    raw_defs: BTreeMap<String, RawTypeDef>,
    resolved_defs: BTreeMap<String, TypeDefinition>,
    visiting: BTreeSet<String>,
}

impl ManifestBuilder {
    fn new(raw_defs: BTreeMap<String, RawTypeDef>) -> Self {
        Self {
            raw_defs,
            resolved_defs: BTreeMap::new(),
            visiting: BTreeSet::new(),
        }
    }

    fn finish_types(self) -> Vec<TypeDefinition> {
        self.resolved_defs.into_values().collect()
    }

    fn export_from_fn(&mut self, item: &ItemFn) -> Result<ExportContract> {
        if has_non_lifetime_generics(&item.sig.generics) {
            anyhow::bail!(
                "export '{}' uses generics. Revenant cannot infer stable TypeScript bindings for generic exports.",
                item.sig.ident
            );
        }
        if item.sig.asyncness.is_some() {
            anyhow::bail!(
                "export '{}' is async. Revenant only supports synchronous #[wasm_bindgen] exports today.",
                item.sig.ident
            );
        }

        let mut args = Vec::new();
        for input in &item.sig.inputs {
            match input {
                FnArg::Receiver(_) => anyhow::bail!(
                    "method export '{}' is not supported. Use free functions for Revenant bindings.",
                    item.sig.ident
                ),
                FnArg::Typed(arg) => {
                    let name = match &*arg.pat {
                        Pat::Ident(ident) => ident.ident.to_string(),
                        _ => anyhow::bail!(
                            "export '{}' uses a destructured parameter. Name each parameter explicitly.",
                            item.sig.ident
                        ),
                    };
                    let ty = self.resolve_type(&arg.ty)?;
                    args.push(FieldContract { name, ty });
                }
            }
        }

        let return_type = match &item.sig.output {
            ReturnType::Default => ContractType::Unit,
            ReturnType::Type(_, ty) => self.resolve_type(ty)?,
        };

        for arg in &args {
            render_direct_type(&arg.ty).with_context(|| {
                format!(
                    "export '{}' cannot be generated because parameter '{}' is not bridgeable",
                    item.sig.ident, arg.name
                )
            })?;
        }
        render_direct_type(&return_type).with_context(|| {
            format!(
                "export '{}' cannot be generated because its return type is not bridgeable",
                item.sig.ident
            )
        })?;

        Ok(ExportContract {
            name: item.sig.ident.to_string(),
            args,
            return_type,
            bridge: BridgeStrategy::Direct,
        })
    }

    fn resolve_type(&mut self, ty: &Type) -> Result<ContractType> {
        match ty {
            Type::Path(path) => self.resolve_path_type(path),
            Type::Reference(reference) => self.resolve_reference_type(reference),
            Type::Tuple(tuple) => Ok(ContractType::Tuple {
                items: tuple
                    .elems
                    .iter()
                    .map(|item| self.resolve_type(item))
                    .collect::<Result<Vec<_>>>()?,
            }),
            Type::Paren(paren) => self.resolve_type(&paren.elem),
            // TODO(v2): explore richer bridge strategies for currently-unsupported
            // shapes (slices, arrays, Vec<String>, structs-by-value, etc.)
            _ => anyhow::bail!(
                "unsupported Rust type '{}'. Revenant currently understands primitives, String, Vec<T>, Option<T>, Result<T, E>, tuples, and named structs/enums.",
                type_to_string(ty)
            ),
        }
    }

    fn resolve_reference_type(&mut self, reference: &syn::TypeReference) -> Result<ContractType> {
        match &*reference.elem {
            Type::Path(path) if path.path.is_ident("str") => Ok(ContractType::String),
            inner => self.resolve_type(inner),
        }
    }

    fn resolve_path_type(&mut self, ty: &syn::TypePath) -> Result<ContractType> {
        let segment = ty
            .path
            .segments
            .last()
            .context("expected a path segment in Rust type")?;
        let ident = segment.ident.to_string();

        if ident == "String" {
            return Ok(ContractType::String);
        }
        if ident == "bool" {
            return Ok(ContractType::Boolean);
        }
        if is_number(&ident) {
            return Ok(ContractType::Number { rust: ident });
        }

        match ident.as_str() {
            "Vec" => {
                let item = first_type_arg(segment)?;
                Ok(ContractType::Vec {
                    item: Box::new(self.resolve_type(item)?),
                })
            }
            "Option" => {
                let item = first_type_arg(segment)?;
                Ok(ContractType::Option {
                    item: Box::new(self.resolve_type(item)?),
                })
            }
            "Result" => {
                let (ok, err) = two_type_args(segment)?;
                Ok(ContractType::Result {
                    ok: Box::new(self.resolve_type(ok)?),
                    err: Box::new(self.resolve_type(err)?),
                })
            }
            _ => {
                if !matches!(segment.arguments, PathArguments::None) {
                    anyhow::bail!(
                        "named type '{}' uses generic arguments. Revenant cannot generate stable bindings for generic named types yet.",
                        ident
                    );
                }

                self.ensure_named_type(&ident)?;
                Ok(ContractType::Named { name: ident })
            }
        }
    }

    fn ensure_named_type(&mut self, name: &str) -> Result<()> {
        if self.resolved_defs.contains_key(name) || self.visiting.contains(name) {
            return Ok(());
        }

        let raw = self.raw_defs.get(name).cloned().with_context(|| {
            format!("type '{name}' is referenced by an export but not defined in rust/src/lib.rs")
        })?;

        self.visiting.insert(name.to_string());

        let resolved = match raw {
            RawTypeDef::Struct(item) => self.resolve_struct(item)?,
            RawTypeDef::Enum(item) => self.resolve_enum(item)?,
        };

        self.visiting.remove(name);
        self.resolved_defs.insert(name.to_string(), resolved);
        Ok(())
    }

    fn resolve_struct(&mut self, item: ItemStruct) -> Result<TypeDefinition> {
        let name = item.ident.to_string();
        if has_non_lifetime_generics(&item.generics) {
            anyhow::bail!(
                "struct '{}' is generic. Revenant cannot generate stable bindings for generic structs yet.",
                name
            );
        }

        match item.fields {
            Fields::Named(fields) => Ok(TypeDefinition::Struct {
                name,
                fields: fields
                    .named
                    .into_iter()
                    .map(|field| {
                        Ok(FieldContract {
                            name: field.ident.context("expected named field")?.to_string(),
                            ty: self.resolve_type(&field.ty)?,
                        })
                    })
                    .collect::<Result<Vec<_>>>()?,
            }),
            Fields::Unnamed(fields) => Ok(TypeDefinition::TupleStruct {
                name,
                items: fields
                    .unnamed
                    .into_iter()
                    .map(|field| self.resolve_type(&field.ty))
                    .collect::<Result<Vec<_>>>()?,
            }),
            Fields::Unit => Ok(TypeDefinition::TupleStruct {
                name,
                items: Vec::new(),
            }),
        }
    }

    fn resolve_enum(&mut self, item: ItemEnum) -> Result<TypeDefinition> {
        let name = item.ident.to_string();
        if has_non_lifetime_generics(&item.generics) {
            anyhow::bail!(
                "enum '{}' is generic. Revenant cannot generate stable bindings for generic enums yet.",
                name
            );
        }

        let variants = item
            .variants
            .into_iter()
            .map(|variant| match variant.fields {
                Fields::Unit => Ok(EnumVariant::Unit {
                    name: variant.ident.to_string(),
                }),
                Fields::Unnamed(fields) => Ok(EnumVariant::Tuple {
                    name: variant.ident.to_string(),
                    items: fields
                        .unnamed
                        .into_iter()
                        .map(|field| self.resolve_type(&field.ty))
                        .collect::<Result<Vec<_>>>()?,
                }),
                Fields::Named(fields) => Ok(EnumVariant::Struct {
                    name: variant.ident.to_string(),
                    fields: fields
                        .named
                        .into_iter()
                        .map(|field| {
                            Ok(FieldContract {
                                name: field.ident.context("expected named field")?.to_string(),
                                ty: self.resolve_type(&field.ty)?,
                            })
                        })
                        .collect::<Result<Vec<_>>>()?,
                }),
            })
            .collect::<Result<Vec<_>>>()?;

        Ok(TypeDefinition::Enum { name, variants })
    }
}

fn first_type_arg(segment: &syn::PathSegment) -> Result<&Type> {
    match &segment.arguments {
        PathArguments::AngleBracketed(args) => args
            .args
            .iter()
            .find_map(|arg| match arg {
                GenericArgument::Type(ty) => Some(ty),
                _ => None,
            })
            .with_context(|| format!("type '{}' is missing its generic parameter", segment.ident)),
        _ => anyhow::bail!(
            "type '{}' must use angle-bracketed generic arguments",
            segment.ident
        ),
    }
}

fn two_type_args(segment: &syn::PathSegment) -> Result<(&Type, &Type)> {
    match &segment.arguments {
        PathArguments::AngleBracketed(args) => {
            let mut types = args.args.iter().filter_map(|arg| match arg {
                GenericArgument::Type(ty) => Some(ty),
                _ => None,
            });
            let first = types.next().with_context(|| {
                format!(
                    "type '{}' is missing its first generic parameter",
                    segment.ident
                )
            })?;
            let second = types.next().with_context(|| {
                format!(
                    "type '{}' is missing its second generic parameter",
                    segment.ident
                )
            })?;
            Ok((first, second))
        }
        _ => anyhow::bail!(
            "type '{}' must use angle-bracketed generic arguments",
            segment.ident
        ),
    }
}

fn is_number(name: &str) -> bool {
    matches!(
        name,
        "i8" | "i16" | "i32" | "u8" | "u16" | "u32" | "f32" | "f64"
    )
}

fn type_to_string(ty: &Type) -> String {
    match ty {
        Type::Path(path) => path
            .path
            .segments
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect::<Vec<_>>()
            .join("::"),
        Type::Reference(reference) => format!("&{}", type_to_string(&reference.elem)),
        Type::Tuple(tuple) => {
            let items = tuple
                .elems
                .iter()
                .map(type_to_string)
                .collect::<Vec<_>>()
                .join(", ");
            format!("({items})")
        }
        Type::Slice(slice) => format!("[{}]", type_to_string(&slice.elem)),
        Type::Array(array) => format!("[{}; N]", type_to_string(&array.elem)),
        Type::Ptr(ptr) => format!(
            "*{} {}",
            if ptr.mutability.is_some() {
                "mut"
            } else {
                "const"
            },
            type_to_string(&ptr.elem)
        ),
        Type::BareFn(_) => "fn(...)".to_string(),
        Type::TraitObject(_) => "dyn Trait".to_string(),
        _ => "unknown".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn manifest_includes_nested_types() {
        let source = r#"
use wasm_bindgen::prelude::*;

pub struct User {
    id: u32,
    tags: Vec<String>,
    state: State,
}

pub enum State {
    Ready,
    Failed { message: String },
}

"#;

        let file = syn::parse_file(source).unwrap();
        let mut raw_defs = BTreeMap::new();
        for item in file.items {
            match item {
                Item::Struct(item) => {
                    raw_defs.insert(item.ident.to_string(), RawTypeDef::Struct(item));
                }
                Item::Enum(item) => {
                    raw_defs.insert(item.ident.to_string(), RawTypeDef::Enum(item));
                }
                _ => {}
            }
        }

        let mut builder = ManifestBuilder::new(raw_defs);
        let ty: Type = syn::parse_str("User").unwrap();
        let resolved = builder.resolve_type(&ty).unwrap();
        let types = builder.finish_types();

        assert!(matches!(resolved, ContractType::Named { ref name } if name == "User"));
        assert_eq!(types.len(), 2);
        assert!(matches!(
            types[0],
            TypeDefinition::Enum { ref name, .. } if name == "State"
        ));
        assert!(matches!(
            types[1],
            TypeDefinition::Struct { ref name, .. } if name == "User"
        ));
    }

    #[test]
    fn wrapper_uses_direct_exports() {
        let source = r#"
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn greet(name: &str) -> String {
    name.to_string()
}

#[wasm_bindgen]
pub fn primes(limit: u32) -> Vec<u32> {
    vec![limit]
}
"#;

        let manifest = build_manifest(source).unwrap();
        let wrapper = generate_wrapper("demo", &manifest).unwrap();
        assert!(wrapper.contains("import * as rawWasm from 'demo_wasm';"));
        assert!(wrapper.contains("export function greet(name: string): string"));
        assert!(wrapper.contains("export function primes(limit: number): Uint32Array"));
    }

    #[test]
    fn complex_runtime_bridge_fails_clearly() {
        let source = r#"
use wasm_bindgen::prelude::*;

pub struct Payload {
    value: String,
}

#[wasm_bindgen]
pub fn save(payload: Payload) -> bool {
    !payload.value.is_empty()
}
"#;

        let err = build_manifest(source).unwrap_err();
        assert!(
            err.to_string()
                .contains("parameter 'payload' is not bridgeable")
        );
    }

    #[test]
    fn lifetime_only_generics_are_bridgeable() {
        let source = r#"
use wasm_bindgen::prelude::*;

pub struct Borrowed<'a> {
    text: &'a str,
}

#[wasm_bindgen]
pub fn greet<'a>(name: &'a str) -> String {
    name.to_string()
}
"#;

        let manifest = build_manifest(source).unwrap();
        assert_eq!(manifest.exports.len(), 1);
        assert_eq!(manifest.exports[0].name, "greet");
    }

    #[test]
    fn wasm_bindgen_impl_block_fails_clearly() {
        let source = r#"
use wasm_bindgen::prelude::*;

pub struct Counter {
    value: u32,
}

#[wasm_bindgen]
impl Counter {
    pub fn new() -> Counter {
        Counter { value: 0 }
    }
}
"#;

        let err = build_manifest(source).unwrap_err();
        assert!(err.to_string().contains("#[wasm_bindgen] impl block"));
    }

    #[test]
    fn unbridgeable_type_is_named_in_error() {
        let source = r#"
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn checksum(data: &[u8]) -> u32 {
    data.len() as u32
}
"#;

        let err = build_manifest(source).unwrap_err();
        assert!(err.to_string().contains("'[u8]'"), "got: {err}");
    }

    #[test]
    fn sync_bindings_writes_manifest_and_wrapper() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();
        let rust_src = root.join(RUST_SUBDIR).join("src");
        let web_lib = root.join(WEB_SUBDIR).join("src").join("lib");
        std::fs::create_dir_all(&rust_src).unwrap();
        std::fs::create_dir_all(&web_lib).unwrap();

        std::fs::write(
            rust_src.join("lib.rs"),
            r#"
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn is_prime(value: u32) -> bool {
    value > 1
}
"#,
        )
        .unwrap();

        sync_bindings(root, "demo").unwrap();

        let manifest =
            std::fs::read_to_string(root.join(WASM_OUT_DIR).join("revenant.contract.json"))
                .unwrap();
        let wrapper = std::fs::read_to_string(web_lib.join("wasm.ts")).unwrap();

        assert!(manifest.contains("\"bridge\": \"direct\""));
        assert!(wrapper.contains("export function is_prime(value: number): boolean"));
    }
}
